// app/layout.js

import "remixicon/fonts/remixicon.css"; // <-- Add this line
import "./globals.css"; // Your TailwindCSS styles

export const metadata = {
  title: "My Portfolio",
  description: "Generated by create-next-app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}